name: Infrastructure CI/CD Pipeline

on:
  workflow_dispatch:

env:
  TF_CLOUD_ORGANIZATION: "1220-IAC"
  CONFIG_DIRECTORY: "./"
  
jobs:
  Deploy_Resources:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure Terraform Cloud API Token
        run: |
          mkdir -p ~/.terraform.d
          echo '{"credentials": {"app.terraform.io": {"token": "${{ secrets.TFE_TOKEN }}"}}}' > ~/.terraform.d/credentials.tfrc.json

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -var="LOGGING_BUCKET_NAME=${{ secrets.LOGGING_BUCKET_NAME }}" -var="LOGGING_BUCKET_KEY=${{ secrets.LOGGING_BUCKET_KEY }}" -var="CLIENT_ID=${{ secrets.CLIENT_ID }}" -var="CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" -var="AUTH_URI=${{ secrets.AUTH_URI }}" -var="TOKEN_URI=${{ secrets.TOKEN_URI }}" -var="AUTH_PROVIDER_CERT_URL=${{ secrets.AUTH_PROVIDER_CERT_URL }}" -var="REDIRECT_URI=${{ secrets.REDIRECT_URI }}" -var="RAW_BUCKET=${{ secrets.RAW_BUCKET }}" -var="RAW_KEY=${{ secrets.RAW_KEY }}" -var="LONG_TERM_TOKEN=${{ secrets.LONG_TERM_TOKEN }}" -var="CHANNELID=${{ secrets.CHANNELID }}" -var="ENDPOINT=${{ secrets.ENDPOINT }}" -var="VIDEO_ENDPOINT=${{ secrets.VIDEO_ENDPOINT }}"
        working-directory: terraform
